=== Nemo64/replicator/examples/calendar/schemas/source-calendar.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",

    "title": "Schema for calendars",
    "description": "Schema for the calendar file",

    "type": "object",
    "required": ["name", "owner", "shared_with", "appointments"],
    "additionalProperties": false,
    "properties": {
        "name": {"type": "string", "minLength": 2, "maxLength": 50},
        "owner": {"type": "string", "format": "email"},
        "shared_with": {"type": "array", "items": {"$ref": "#/definitions/share"}},
        "appointments": {"type": "array", "items": {"$ref": "#/definitions/appointment"}}
    },

    "definitions": {
        "share": {
            "type": "object",
            "required": ["user", "privilege"],
            "additionalProperties": false,
            "properties": {
                "user": {"type": "string", "format": "email"},
                "privilege": {"type": "string", "enum": ["read-only", "edit"]}
            }
        },
        "appointment": {
            "type": "object",
            "required": ["time", "name"],
            "additionalProperties": false,
            "properties": {
                "time": {"type": "string", "format": "date-time"},
                "name": {"type": "string", "minLength": 2, "maxLength": 50}
            }
        }
    }
}

=== Nemo64/replicator/examples/calendar/source/2732158b-aaa3-4951-aa40-6e9cbac328d0.json
{
    "name": "Work events",
    "owner": "user+1@example.com",
    "shared_with": [
        {"user": "user+2@example.com", "privilege": "read-only"}
    ],
    "appointments": [
        {"time": "2021-06-07T10:00:00+02:00", "name": "Morning Meeting"},
        {"time": "2021-06-14T10:00:00+02:00", "name": "Morning Meeting"},
        {"time": "2021-06-21T10:00:00+02:00", "name": "Morning Meeting"},
        {"time": "2021-06-28T10:00:00+02:00", "name": "Morning Meeting"},
        {"time": "2021-07-05T10:00:00+02:00", "name": "Morning Meeting"},
        {"time": "2021-07-12T10:00:00+02:00", "name": "Morning Meeting"},
        {"time": "2021-07-26T10:00:00+02:00", "name": "Morning Meeting"}
    ]
}

=== Nemo64/replicator/examples/calendar/source/6ff6255b-45b5-4895-8d59-50fa60663cfc.json
{
    "name": "Personal",
    "owner": "user+1@example.com",
    "shared_with": [
        {"user": "user+2@example.com", "privilege": "read-only"}
    ],
    "appointments": [
        {"time": "2021-06-28T06:00:00+02:00", "name": "Car inspection"},
        {"time": "2021-07-03T13:30:00+02:00", "name": "Doctor"},
        {"time": "2021-07-04T20:00:00+02:00", "name": "Dinner"}
    ]
}
